### ISSUE TITLE
Doesn't work on WSL2

### ISSUE THREAD

**Issue by andresclari** [misogi/vscode-ruby-rubocop#103]
On WSL2 with rvm, rubocop fails to start with the following error:

```
/home/andrew/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:284: in `find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException) from /home/andrew/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path' from /home/andrew/.rvm/gems/ruby-2.6.3@senitron/bin/rubocop:23:in `<main>'
```

using path:
```json
"ruby.rubocop.executePath": "/home/andrew/.rvm/gems/ruby-2.6.3@senitron/bin/"
```

**Comment by eric-wood** [comment]
I'm running into the same error with rvm on MacOS. I've entered the executable path as it appears when I do `which rubocop`, but it errors out.

My `executePath` setting is: `/Users/eric/.rvm/gems/ruby-2.5.0/bin/`

**Comment by DaveSanders** [comment]
Same here. Any ideas?  I know that RVM isn't really the ideal way per the docs, but its pretty standard way to manage ruby versions...

**Comment by rajdeep26** [comment]
Did anyone resolve this issue? I am facing the same issue on the mac.

Ruby:
```
rajdeep$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
```

Rubocop:
```
rajdeep$ which rubocop
/Users/rajdeep/.rvm/gems/ruby-2.7.0@myproject/bin/rubocop
```

Vscode Settings.json
```
"ruby.rubocop.executePath": "/Users/rajdeep/.rvm/gems/ruby-2.7.0@myproject/bin/"
```

Error trace:
```
/Users/rajdeep/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException) from 
/Users/rajdeep/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path' from 
/Users/rajdeep/.rvm/gems/ruby-2.7.0@thrillophilia-common/bin/rubocop:23:in `<main>' from 
/Users/rajdeep/.rvm/rubies/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval' from 
/Users/rajdeep/.rvm/rubies/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by CharlieIGG** [comment]
Hey @rajdeep26 did you find a solution for this?

**Comment by rajdeep26** [comment]
Hey @CharlieIGG, Nope. But you can try `solargraph` instead of this extension. It provides Rubocop support and more.

**Comment by CharlieIGG** [comment]
Thanks @rajdeep26 !

**Comment by sharq1** [comment]
Still doesn't work for me - neither standalone or using solargraph. It doesn't show any execution errors in VS code but doesn't highlight any code either.
Using rbenv and tweaked execute path to `/home/sharq/.rbenv/shims/`.
Tried toggling `use bundler` option but the result is the same.

**Comment by CornerstoneII** [comment]
/bin/sh: 1: /home/bilegyr/.rvm/gems/ruby-2.7.2/bin/rubocoprubocop: not found

I've come to believe it has something to do with .rvm because it never happened before with rbenv on my former machine.

**Comment by AndrewKvalheim** [comment]
> `rubocoprubocop: not found`

This extension is unusual in that its configuration accepts a path prefix, not the actual path to the executable. For example:

https://github.com/misogi/vscode-ruby-rubocop/blob/c660296bb5034ea4c3d97993a44ecc5094d77e9c/README.md?plain=1#L65-L67

Note that it performs no path resolution and applies naive string concatenation instead of path joining—

https://github.com/misogi/vscode-ruby-rubocop/blob/c660296bb5034ea4c3d97993a44ecc5094d77e9c/src/configuration.ts#L57

—so you must provide the joining slash.
