### ISSUE TITLE
rubocop returns empty output! please check configuration.

### ISSUE THREAD

**Issue by resistorsoftware** [misogi/vscode-ruby-rubocop#132]
At the command line I do a which rubucop and get my path:

    /Users/sodapop/.rvm/gems/ruby-2.7.0/bin/rubocop

It works fine. If I paste that into the User and Workspace settings for the path:
    
    /Users/sodapop/.rvm/gems/ruby-2.7.0/bin/

I get the error **rubocop returns empty output! please check configuration.**

I am not sure why this is. This extension seems unable to activate rubocop correctly. What is typically wrong with configurations where you provide the correct path to the executable, but get empty output?

**Comment by zhelyan** [comment]
seems to be caused by 

```
Error: Error parsing autocorrection from CLI: 
{
  "metadata": {
    "rubocop_version": "0.92.0",
    "ruby_engine": "ruby",
    "ruby_version": "2.7.1",
    "ruby_patchlevel": "83",
    "ruby_platform": "x86_64-darwin19"
  },
  "files": [
    {
      "path": "lib/foo/bar.rb",
      "offenses": [
        {
          "severity": "convention",
          "message": "Inconsistent indentation detected. (https://rubystyle.guide#spaces-indentation, https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#follow-the-coding-conventions)",
          "cop_name": "Layout/IndentationConsistency",
          "corrected": true,
          "correctable": true,
          "location": {
            "start_line": 17,
            "start_column": 7,
            "last_line": 29,
            "last_column": 11,
            "length": 622,
            "line": 17,
            "column": 7
          }
        }
  ],
  "summary": {
    "offense_count": 1,
    "target_file_count": 1,
    "inspected_file_count": 1
  }
}

	at RubocopAutocorrectProvider.onSuccess (/Users/me/.vscode/extensions/misogi.ruby-rubocop-0.8.4/out/src/rubocop.js:54:19)
```

**Comment by psolvy** [comment]
> seems to be caused by
> 
> ```
> Error: Error parsing autocorrection from CLI: 
> {
>   "metadata": {
>     "rubocop_version": "0.92.0",
>     "ruby_engine": "ruby",
>     "ruby_version": "2.7.1",
>     "ruby_patchlevel": "83",
>     "ruby_platform": "x86_64-darwin19"
>   },
>   "files": [
>     {
>       "path": "lib/foo/bar.rb",
>       "offenses": [
>         {
>           "severity": "convention",
>           "message": "Inconsistent indentation detected. (https://rubystyle.guide#spaces-indentation, https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#follow-the-coding-conventions)",
>           "cop_name": "Layout/IndentationConsistency",
>           "corrected": true,
>           "correctable": true,
>           "location": {
>             "start_line": 17,
>             "start_column": 7,
>             "last_line": 29,
>             "last_column": 11,
>             "length": 622,
>             "line": 17,
>             "column": 7
>           }
>         }
>   ],
>   "summary": {
>     "offense_count": 1,
>     "target_file_count": 1,
>     "inspected_file_count": 1
>   }
> }
> 
> 	at RubocopAutocorrectProvider.onSuccess (/Users/me/.vscode/extensions/misogi.ruby-rubocop-0.8.4/out/src/rubocop.js:54:19)
> ```

same with rubocop 0.92.0

**Comment by AndreeWille** [comment]
I get this error everytime i save a file. Also formatting a ruby file does not work because of this error.

rubocop: 0.92.0
vs-ruby-rubocop: 0.8.4
OS: WSL2 with Ubuntu 20.04 on Windows 10

**Comment by ngouy** [comment]
see https://github.com/misogi/vscode-ruby-rubocop/pull/131, it should fix ur issue. It's in fact a dup of #123

**Comment by jonstump** [comment]
I'm still seeing this message and I set up my settings.json to point to /home/jmstump/.rbenv/shims/

Rubocop runs in other editors so it seems to be either related to the extension or my setup of it.

**Comment by ngouy** [comment]
I see it pop time to time since some days also, my guess is that there is something that broke again, but it's not consistent on my machine (depend on the content of the file itself and the rubocop version is seems)

If you find a way to 100% reproduce it would be glad to try

**Comment by jonstump** [comment]
@ngouy I ended up disabling linting in ruby altogether because a recent update broke it while using live share (basically the only reason I use VSCode). I'll see if I can give it another try and get you some more information.

**Comment by DRBragg** [comment]
Just started getting this pop up after the last VSCode update (1.55.0)

**Comment by ngouy** [comment]
I am a bit underwater rn and it works for me so ... Will probably check it out when it will break for me and it makes me loses time. Sorry guys

For the live share it's way out of my reach, sorry

**Comment by filipemendespi** [comment]
I tried several solutions and I was only able to solve the problem by removing the visual code via flatpak and downloading the .deb.
In my case I am using pop_os.

**Comment by yangjindong** [comment]
This worked for me according this [post](https://newbedev.com/rubocop-on-vscode-not-working-error-rubocop-is-not-executable): 
```
{
  // If not specified searches for 'rubocop' executable available on PATH (default and recommended)
  "ruby.rubocop.executePath": "",
  ...
}
```
