### ISSUE TITLE
Unexpected token u: SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by orospakr** [misogi/vscode-ruby-rubocop#17]
Tried using the extension, nothing happens on save/manually running "Execute rubocop", discovered this in the Console:

```
shell.ts:416Unexpected token u: SyntaxError: Unexpected token u
    at Object.parse (native)
    at onDidExec (/Users/orospakr/.vscode/extensions/misogi.ruby-rubocop-0.2.0/out/src/rubocop.js:40:32)
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by misogi** [comment]
This extension expect JSON output by rubocop.
In this case, command outputs non-JSON output by some reason (I don't know reason).

I released version 0.2.1.
New version catches this case and output exclusive message and (few length of) raw output.
