### ISSUE TITLE
Use project directory's rvm ruby version

### ISSUE THREAD

**Issue by ctsstc** [misogi/vscode-ruby-rubocop#89]
The VSCode Rubocop extension should be using the current project's rvm/ruby version instead of the system default. The extension should be utilizing the same dependencies as the current project.

## Problem

When you are using something like `rubocop-rspec` it will install to the project's ruby version, but the rubocop extension will not have access to the correct dependant gems because it's using a different version that doesn't have that gem installed.

## Error Codes

When the extension tries to run I see something like this pop up:

```
cannot load such file -- rubocop-rspec /Users/codyswartz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require' /Users/codyswartz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_loader_resolver.rb:11:in `each' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_loader.rb:43:in `load_file' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_loader.rb:82:in `configuration_from_file' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.58.2/lib/rubocop/config_store.rb:44:in `for' /Users/codyswartz/.rvm/gems/ruby-2.4.1/gems/rubocop-0.5...
```

**Comment by ctsstc** [comment]
For now I switched my rvm over to the version the extension is running and installed the gems manually, but this isn't the greatest fix out there : \

**Comment by gokuu** [comment]
If you're installing `rubocop` in your app's bundle, maybe the PR I just opened (#91) can be of use to  you too.

**Comment by yelvert** [comment]
This is a very hacky solution, but its working well for me. I created this file in my projects bin directory:

`bin/vscode_rubocop`
```bash
#! /usr/bin/env bash -l
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.."
cd "${DIR}"
rvm . do bin/rubocop "$@"
```

Then set the `executePath` to `bin/vscode_`.

This assumes you have rubocop binstubbed.

**Comment by ctsstc** [comment]
@gokuu seems that I'm getting similar errors when I have that enabled. The runner seems to use rmv's system default rather than the directory version

**Comment by ctsstc** [comment]
I'm back searching again, I'm back on a project that's not updated.

@gokuu when I use the new `Use Bundler` it seems to be using the system default of `rvm` so then I get an error like: 

```
Bundler::RubyVersionMismatch: Your Ruby version is 2.6.2, but your Gemfile specified 2.6.3 
```

**Comment by ctsstc** [comment]
Thanks @yelvert that seems to be the only solution I can get to work. I wish I could do this at a system level and not per-project, but other solutions I tried seemed to lack the context of the current environment/folder when nvm tries to determine which version to use.

**Comment by ctsstc** [comment]
Here's the one thing that actually worked for me, but it's also the worst since it requires a per-project configuration and you are likely to fight your versoning, unless you add it as a global ignore or commit it.

https://github.com/misogi/vscode-ruby-rubocop/issues/89#issuecomment-596040029
https://github.com/misogi/vscode-ruby-rubocop/issues/89#issuecomment-636978597

**Comment by limcross** [comment]
I think I have found a more maintainable way to fix this among all the projects you have. On the settings set `rvm . do bin/bundle exec ` (with a space character at the end). Just that, is really easy. 👌

**Comment by jeremybdk** [comment]
@limcross tried your solution and I'm still running into an issue and cannot seems to figure it out, I'm using zsh, and when I use your fix I get this error: /bin/sh: rvm: command not found.
I wonder if anyone has an idea,

Thanks for the help
